#!/bin/sh

git add .bash_logout
git add .bash_profile
git add .bashrc
git add .config/calcurse/
git add .config/dunst/
git add .config/emacs/
git add .config/fontconfig/
git add .config/gtk-2.0/
git add .config/gtk-3.0/
git add .config/htop/
git add .config/mimeapps.list
git add .config/mpd/
git add .config/mpv/
git add .config/ncmpcpp/
git add .config/neofetch/
git add .config/nvim/
git add .config/pulse/daemon.conf
git add .config/shell/
git add .config/sxiv/
git add .config/user-dirs.dirs
git add .config/wal/
git add .config/wget/
git add .config/x11/
git add .config/zathura/
git add .config/zsh/
git add .local/bin/
git add .local/share/bg.png
git add .local/share/bg
git add .local/share/weatherreport
git add .local/share/applications/
git add .xprofile
git add .zprofile
git add .config/keynav/
git add README.md 
git add faids/
git add .local/bin/booksplit
git add .local/bin/compiler
git add .local/bin/cron/
git add .local/bin/displayselect
git add .local/bin/dmenuhandler
git add .local/bin/dmenumount
git add .local/bin/dmenumountcifs
git add .local/bin/dmenupass
git add .local/bin/dmenurecord
git add .local/bin/dmenuumount
git add .local/bin/dmenuunicode
git add .local/bin/getbib
git add .local/bin/getkeys
git add .local/bin/ifinstalled
git add .local/bin/lfub
git add .local/bin/linkhandler
git add .local/bin/maimpick
git add .local/bin/noisereduce
git add .local/bin/opout
git add .local/bin/otp
git add .local/bin/pauseallmpv
git add .local/bin/peertubetorrent
git add .local/bin/podentr
git add .local/bin/prompt
git add .local/bin/qndl
git add .local/bin/queueandnotify
git add .local/bin/remaps
git add .local/bin/rotdir
git add .local/bin/rssadd
git add .local/bin/samedir
git add .local/bin/setbg
git add .local/bin/shortcuts
git add .local/bin/slider
git add .local/bin/statusbar/
git add .local/bin/sysact
git add .local/bin/tag
git add .local/bin/td-toggle
git add .local/bin/texclear
git add .local/bin/torwrap
git add .local/bin/transadd
git add .local/bin/tutorialvids
git add .local/bin/unix
