(deftheme tty-dark)

(custom-theme-set-faces
 'tty-dark
 '(mode-line ((t (:background "black" :foreground "white"))))
 '(font-lock-comment-face ((t (:foreground "green" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "green" :slant italic))))
 '(font-lock-doc-face ((t (:foreground "green" :slant italic))))
 '(dired-directory ((t (:foreground "green"))))
 '(elisp-shorthand-font-lock-face ((t (:foreground "white"))))
 '(font-lock-bracket-face ((t (:foreground "white"))))
 '(font-lock-builtin-face ((t (:foreground "white"))))
 '(font-lock-constant-face ((t (:foreground "white"))))
 '(font-lock-delimiter-face ((t (:foreground "white"))))
 '(font-lock-doc-markup-face ((t (:foreground "white"))))
 '(font-lock-escape-face ((t (:foreground "white"))))
 '(font-lock-function-call-face ((t (:foreground "white"))))
 '(font-lock-function-name-face ((t (:foreground "white"))))
 '(font-lock-keyword-face ((t (:foreground "white"))))
 '(font-lock-misc-punctuation-face ((t (:foreground "white"))))
 '(font-lock-negation-char-face ((t (:foreground "white"))))
 '(font-lock-number-face ((t (:foreground "white"))))
 '(font-lock-operator-face ((t (:foreground "white"))))
 '(font-lock-preprocessor-face ((t (:foreground "white"))))
 '(font-lock-property-name-face ((t (:foreground "white"))))
 '(font-lock-property-use-face ((t (:foreground "white"))))
 '(font-lock-punctuation-face ((t (:foreground "white"))))
 '(font-lock-regexp-face ((t (:foreground "white"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "white"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "white"))))
 '(font-lock-string-face ((t (:foreground "white"))))
 '(font-lock-type-face ((t (:foreground "white"))))
 '(font-lock-variable-name-face ((t (:foreground "white"))))
 '(font-lock-variable-use-face ((t (:foreground "white"))))
 '(font-lock-warning-face ((t (:foreground "white"))))
 '(erc-prompt-face ((t (:background "black" :foreground "white" :weight bold))))
 '(erc-default-face ((t (:foreground "white"))))
 '(erc-notice-face ((t (:foreground "blue"))))
 '(erc-action-face ((t (:foreground "magenta" :weight bold))))
 '(erc-direct-msg-face ((t (:foreground "magenta"))))
 '(erc-error-face ((t (:foreground "red" :weight bold))))
 '(erc-my-nick-face ((t (:foreground "cyan" :weight bold))))
 '(erc-current-nick-face ((t (:foreground "yellow" :weight bold))))
 '(erc-nick-default-face ((t (:foreground "blue"))))
 '(erc-pal-face ((t (:foreground "magenta" :weight bold))))
 '(erc-fool-face ((t (:foreground "blue"))))
 '(erc-timestamp-face ((t (:foreground "green"))))
 '(erc-header-line ((t (:background "black" :foreground "white"))))
 '(erc-input-face ((t (:foreground "white"))))
 '(erc-keyword-face ((t (:foreground "yellow" :weight bold))))
 '(erc-dangerous-host-face ((t (:foreground "red" :weight bold))))
 '(vertico-current ((t (:inverse-video t))))
 '(region ((t (:background "white" :foreground "black"))))
 '(vertico-group-title ((t (:foreground "white" :weight bold))))
 '(vertico-multiline ((t (:foreground "white"))))
 '(line-number ((t (:background "black" :foreground "gray"))))
 '(line-number-current-line ((t (:background "black" :foreground "white" :weight bold))))
 '(vertical-border ((t (:background "black" :foreground "gray"))))
 '(window-divider ((t (:background "black" :foreground "gray")))))

(provide-theme 'tty-dark)
