(deftheme tty-dark)

(custom-theme-set-faces
 'tty-dark
 '(mode-line ((t (:background "black" :foreground "white"))))
 '(font-lock-comment-face ((t (:foreground "green" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "green" :slant italic))))
 '(font-lock-doc-face ((t (:foreground "green" :slant italic))))
 '(erc-prompt-face ((t (:background "black" :foreground "white" :weight bold))))
 '(erc-default-face ((t (:foreground "white"))))
 '(erc-notice-face ((t (:foreground "blue"))))
 '(erc-action-face ((t (:foreground "magenta" :weight bold))))
 '(erc-direct-msg-face ((t (:foreground "magenta"))))
 '(erc-error-face ((t (:foreground "red" :weight bold))))
 '(erc-my-nick-face ((t (:foreground "cyan" :weight bold))))
 '(erc-current-nick-face ((t (:foreground "yellow" :weight bold))))
 '(erc-nick-default-face ((t (:foreground "blue"))))
 '(erc-pal-face ((t (:foreground "magenta" :weight bold))))
 '(erc-fool-face ((t (:foreground "blue"))))
 '(erc-timestamp-face ((t (:foreground "green"))))
 '(erc-header-line ((t (:background "black" :foreground "white"))))
 '(erc-input-face ((t (:foreground "white"))))
 '(erc-keyword-face ((t (:foreground "yellow" :weight bold))))
 '(erc-dangerous-host-face ((t (:foreground "red" :weight bold))))
 '(vertico-current ((t (:background "blue" :foreground "white" :weight bold))))
 '(region ((t (:background "blue" :foreground "white" :weight bold))))
 '(vertico-group-title ((t (:foreground "white" :weight bold))))
 '(vertico-multiline ((t (:foreground "white"))))
 '(line-number ((t (:background "black" :foreground "gray"))))
 '(line-number-current-line ((t (:background "black" :foreground "white" :weight bold)))))

(provide-theme 'tty-dark)
