;;; tty-dark-theme.el --- Minimal black and white theme for TTY -*- lexical-binding: t; -*-

;; Author: fff
;; Version: 1.0
;; Package-Requires: ((emacs "24.1"))

;;; Commentary:
;; A minimal monochrome theme for TTY usage.
;; Black background, white foreground, no syntax highlighting.

;;; Code:

(deftheme tty-dark
  "Minimal black/white theme for TTY.")

(let ((class-8 '((class color) (min-colors 8)))
      (class-88 '((class color) (min-colors 88))))
  (custom-theme-set-faces
   'tty-dark

   ;; Base faces
   `(default ((,class-88 (:background "#000000" :foreground "#ffffff"))
              (,class-8 (:background "black" :foreground "white"))))
   `(cursor ((,class-88 (:background "#ffffff"))
             (,class-8 (:background "white"))))
   `(fringe ((,class-88 (:background "#000000" :foreground "#ffffff"))
             (,class-8 (:background "black" :foreground "white"))))
   `(border ((,class-88 (:background "#000000"))
             (,class-8 (:background "black"))))
   `(hl-line ((,class-88 (:background "#333333"))
              (,class-8 (:background "gray20"))))

   ;; Mode-line
   `(mode-line ((,class-88 (:background "#000000" :foreground "#ffffff" :box nil))
                (,class-8 (:background "black" :foreground "white" :box nil))))
   `(mode-line-inactive ((,class-88 (:background "#000000" :foreground "#888888" :box nil))
                         (,class-8 (:background "black" :foreground "gray" :box nil))))
   `(mode-line-buffer-id ((,class-88 (:foreground "white" :weight bold))
                          (,class-8 (:foreground "white" :weight bold))))
   `(mode-line-emphasis ((,class-88 (:foreground "white" :weight bold))
                         (,class-8 (:foreground "white" :weight bold))))
   `(mode-line-highlight ((,class-88 (:foreground "white"))
                          (,class-8 (:foreground "white"))))

   ;; Minibuffer and prompts
   `(minibuffer-prompt ((,class-88 (:foreground "white" :weight bold))
                        (,class-8 (:foreground "white" :weight bold))))
   `(header-line ((,class-88 (:background "#000000" :foreground "#ffffff"))
                  (,class-8 (:background "black" :foreground "white"))))

   ;; Highlighting - needs to be visible
   `(region ((,class-88 (:background "#000044" :foreground "white"))
             (,class-8 (:background "blue" :foreground "white"))))
   `(secondary-selection ((,class-88 (:background "#333333"))
                          (,class-8 (:background "gray30"))))
   `(highlight ((,class-88 (:background "#000044" :foreground "white"))
                (,class-8 (:background "blue" :foreground "white"))))
   `(isearch ((,class-88 (:background "#af00ff" :foreground "white" :weight bold))
              (,class-8 (:background "magenta" :foreground "white" :weight bold))))
   `(lazy-highlight ((,class-88 (:background "#000044" :foreground "white"))
                     (,class-8 (:background "blue" :foreground "white"))))
   `(match ((,class-88 (:background "#000044" :foreground "white"))
            (,class-8 (:background "blue" :foreground "white"))))

   ;; Line numbers
   `(line-number ((,class-88 (:background "#000000" :foreground "#888888"))
                  (,class-8 (:background "black" :foreground "gray"))))
   `(line-number-current-line ((,class-88 (:background "#000000" :foreground "#ffffff" :weight bold))
                               (,class-8 (:background "black" :foreground "white" :weight bold))))

   ;; Font Lock - all white (no syntax highlighting)
   `(font-lock-builtin-face ((,class-88 (:foreground "white"))
                             (,class-8 (:foreground "white"))))
   `(font-lock-comment-face ((,class-88 (:foreground "white"))
                             (,class-8 (:foreground "white"))))
   `(font-lock-comment-delimiter-face ((,class-88 (:foreground "white"))
                                       (,class-8 (:foreground "white"))))
   `(font-lock-constant-face ((,class-88 (:foreground "white"))
                              (,class-8 (:foreground "white"))))
   `(font-lock-doc-face ((,class-88 (:foreground "white"))
                         (,class-8 (:foreground "white"))))
   `(font-lock-function-name-face ((,class-88 (:foreground "white"))
                                   (,class-8 (:foreground "white"))))
   `(font-lock-keyword-face ((,class-88 (:foreground "white"))
                             (,class-8 (:foreground "white"))))
   `(font-lock-negation-char-face ((,class-88 (:foreground "white"))
                                   (,class-8 (:foreground "white"))))
   `(font-lock-preprocessor-face ((,class-88 (:foreground "white"))
                                  (,class-8 (:foreground "white"))))
   `(font-lock-regexp-grouping-backslash ((,class-88 (:foreground "white"))
                                          (,class-8 (:foreground "white"))))
   `(font-lock-regexp-grouping-construct ((,class-88 (:foreground "white"))
                                          (,class-8 (:foreground "white"))))
   `(font-lock-string-face ((,class-88 (:foreground "white"))
                            (,class-8 (:foreground "white"))))
   `(font-lock-type-face ((,class-88 (:foreground "white"))
                          (,class-8 (:foreground "white"))))
   `(font-lock-variable-name-face ((,class-88 (:foreground "white"))
                                   (,class-8 (:foreground "white"))))
   `(font-lock-warning-face ((,class-88 (:foreground "white" :weight bold))
                             (,class-8 (:foreground "white" :weight bold))))

   ;; Completions and selection
   `(completions-common-part ((,class-88 (:foreground "white"))
                              (,class-8 (:foreground "white"))))
   `(completions-first-difference ((,class-88 (:foreground "white" :weight bold))
                                   (,class-8 (:foreground "white" :weight bold))))
   `(icomplete-first-match ((,class-88 (:background "#000044" :foreground "white" :weight bold))
                            (,class-8 (:background "blue" :foreground "white" :weight bold))))

   ;; Vertico
   `(vertico-current ((,class-88 (:background "#000044" :foreground "white" :weight bold))
                      (,class-8 (:background "blue" :foreground "white" :weight bold))))
   `(vertico-group-title ((,class-88 (:foreground "white" :weight bold))
                          (,class-8 (:foreground "white" :weight bold))))
   `(vertico-group-separator ((,class-88 (:foreground "white"))
                              (,class-8 (:foreground "white"))))
   `(vertico-multiline ((,class-88 (:foreground "white"))
                        (,class-8 (:foreground "white"))))

   ;; Dired
   `(dired-directory ((,class-88 (:foreground "white" :weight bold))
                      (,class-8 (:foreground "white" :weight bold))))
   `(dired-flagged ((,class-88 (:foreground "white" :weight bold))
                    (,class-8 (:foreground "white" :weight bold))))
   `(dired-header ((,class-88 (:foreground "white" :weight bold))
                   (,class-8 (:foreground "white" :weight bold))))
   `(dired-ignored ((,class-88 (:foreground "gray"))
                    (,class-8 (:foreground "gray"))))
   `(dired-mark ((,class-88 (:foreground "white" :weight bold))
                 (,class-8 (:foreground "white" :weight bold))))
   `(dired-marked ((,class-88 (:foreground "white" :weight bold))
                   (,class-8 (:foreground "white" :weight bold))))
   `(dired-perm-write ((,class-88 (:foreground "white"))
                       (,class-8 (:foreground "white"))))
   `(dired-symlink ((,class-88 (:foreground "white"))
                    (,class-8 (:foreground "white"))))
   `(dired-warning ((,class-88 (:foreground "white" :weight bold))
                    (,class-8 (:foreground "white" :weight bold))))

   ;; Org mode
   `(org-level-1 ((,class-88 (:foreground "white" :weight bold))
                  (,class-8 (:foreground "white" :weight bold))))
   `(org-level-2 ((,class-88 (:foreground "white" :weight bold))
                  (,class-8 (:foreground "white" :weight bold))))
   `(org-level-3 ((,class-88 (:foreground "white" :weight bold))
                  (,class-8 (:foreground "white" :weight bold))))
   `(org-level-4 ((,class-88 (:foreground "white"))
                  (,class-8 (:foreground "white"))))
   `(org-level-5 ((,class-88 (:foreground "white"))
                  (,class-8 (:foreground "white"))))
   `(org-level-6 ((,class-88 (:foreground "white"))
                  (,class-8 (:foreground "white"))))
   `(org-level-7 ((,class-88 (:foreground "white"))
                  (,class-8 (:foreground "white"))))
   `(org-level-8 ((,class-88 (:foreground "white"))
                  (,class-8 (:foreground "white"))))

   ;; Magit
   `(magit-section-heading ((,class-88 (:foreground "white" :weight bold))
                            (,class-8 (:foreground "white" :weight bold))))
   `(magit-section-highlight ((,class-88 (:background "#333333"))
                              (,class-8 (:background "gray20"))))
   `(magit-diff-context ((,class-88 (:foreground "white"))
                         (,class-8 (:foreground "white"))))
   `(magit-diff-context-highlight ((,class-88 (:background "#333333" :foreground "white"))
                                   (,class-8 (:background "gray20" :foreground "white"))))

   ;; Doom modeline - force black background
   `(doom-modeline-bar ((,class-88 (:background "#000000"))
                        (,class-8 (:background "black"))))
   `(doom-modeline-bar-inactive ((,class-88 (:background "#000000"))
                                 (,class-8 (:background "black"))))
   `(doom-modeline-buffer-file ((,class-88 (:foreground "white"))
                                (,class-8 (:foreground "white"))))
   `(doom-modeline-buffer-modified ((,class-88 (:foreground "white"))
                                    (,class-8 (:foreground "white"))))
   `(doom-modeline-buffer-major-mode ((,class-88 (:foreground "white"))
                                      (,class-8 (:foreground "white"))))
   `(doom-modeline-buffer-path ((,class-88 (:foreground "white"))
                                (,class-8 (:foreground "white"))))
   `(doom-modeline-project-dir ((,class-88 (:foreground "white"))
                                (,class-8 (:foreground "white"))))
   `(doom-modeline-project-root-dir ((,class-88 (:foreground "white"))
                                     (,class-8 (:foreground "white"))))
   `(doom-modeline-info ((,class-88 (:foreground "white"))
                         (,class-8 (:foreground "white"))))
   `(doom-modeline-warning ((,class-88 (:foreground "white"))
                            (,class-8 (:foreground "white"))))
   `(doom-modeline-urgent ((,class-88 (:foreground "white"))
                           (,class-8 (:foreground "white"))))
   `(doom-modeline-evil-normal-state ((,class-88 (:foreground "white"))
                                      (,class-8 (:foreground "white"))))
   `(doom-modeline-evil-insert-state ((,class-88 (:foreground "white"))
                                      (,class-8 (:foreground "white"))))
   `(doom-modeline-evil-visual-state ((,class-88 (:foreground "white"))
                                      (,class-8 (:foreground "white"))))
   `(doom-modeline-evil-replace-state ((,class-88 (:foreground "white"))
                                       (,class-8 (:foreground "white"))))
   `(doom-modeline-evil-operator-state ((,class-88 (:foreground "white"))
                                        (,class-8 (:foreground "white"))))
   `(doom-modeline-evil-emacs-state ((,class-88 (:foreground "white"))
                                     (,class-8 (:foreground "white"))))
   `(doom-modeline-evil-motion-state ((,class-88 (:foreground "white"))
                                      (,class-8 (:foreground "white"))))

   ;; Show Paren
   `(show-paren-match ((,class-88 (:background "#000044" :foreground "white" :weight bold))
                       (,class-8 (:background "dark blue" :foreground "white" :weight bold))))
   `(show-paren-mismatch ((,class-88 (:background "red" :foreground "white" :weight bold))
                          (,class-8 (:background "red" :foreground "white" :weight bold))))

   ;; Error/Warning/Success
   `(error ((,class-88 (:foreground "white" :weight bold))
            (,class-8 (:foreground "white" :weight bold))))
   `(warning ((,class-88 (:foreground "white" :weight bold))
              (,class-8 (:foreground "white" :weight bold))))
   `(success ((,class-88 (:foreground "white" :weight bold))
              (,class-8 (:foreground "white" :weight bold))))

   ;; Links
   `(link ((,class-88 (:foreground "white" :underline t))
           (,class-8 (:foreground "white" :underline t))))
   `(link-visited ((,class-88 (:foreground "white" :underline t))
                   (,class-8 (:foreground "white" :underline t))))

   ;; UI & Borders
   `(vertical-border ((,class-88 (:background "#000000" :foreground "#ffffff"))
                      (,class-8 (:background "black" :foreground "white"))))
   `(window-divider ((,class-88 (:background "#000000" :foreground "#ffffff"))
                     (,class-8 (:background "black" :foreground "white"))))
   `(window-divider-first-pixel ((,class-88 (:background "#000000" :foreground "#ffffff"))
                                 (,class-8 (:background "black" :foreground "white"))))
   `(window-divider-last-pixel ((,class-88 (:background "#000000" :foreground "#ffffff"))
                                (,class-8 (:background "black" :foreground "white"))))
   `(internal-border ((,class-88 (:background "#000000"))
                      (,class-8 (:background "black"))))

   ;; ERC
   `(erc-default-face ((,class-88 (:background "#000000" :foreground "#ffffff"))
                       (,class-8 (:background "black" :foreground "white"))))
   `(erc-action-face ((,class-88 (:foreground "white" :weight bold))
                      (,class-8 (:foreground "white" :weight bold))))
   `(erc-bold-face ((,class-88 (:weight bold))
                    (,class-8 (:weight bold))))
   `(erc-current-nick-face ((,class-88 (:foreground "white" :weight bold))
                            (,class-8 (:foreground "white" :weight bold))))
   `(erc-dangerous-host-face ((,class-88 (:foreground "white" :weight bold))
                              (,class-8 (:foreground "white" :weight bold))))
   `(erc-direct-msg-face ((,class-88 (:foreground "white"))
                          (,class-8 (:foreground "white"))))
   `(erc-error-face ((,class-88 (:foreground "white" :weight bold))
                     (,class-8 (:foreground "white" :weight bold))))
   `(erc-fool-face ((,class-88 (:foreground "gray"))
                    (,class-8 (:foreground "gray"))))
   `(erc-header-line ((,class-88 (:background "#000000" :foreground "#ffffff"))
                      (,class-8 (:background "black" :foreground "white"))))
   `(erc-input-face ((,class-88 (:foreground "white"))
                     (,class-8 (:foreground "white"))))
   `(erc-inverse-face ((,class-88 (:background "#ffffff" :foreground "#000000"))
                       (,class-8 (:background "white" :foreground "black"))))
   `(erc-keyword-face ((,class-88 (:foreground "white" :weight bold))
                       (,class-8 (:foreground "white" :weight bold))))
   `(erc-my-nick-face ((,class-88 (:foreground "white" :weight bold))
                       (,class-8 (:foreground "white" :weight bold))))
   `(erc-nick-default-face ((,class-88 (:foreground "white"))
                            (,class-8 (:foreground "white"))))
   `(erc-nick-msg-face ((,class-88 (:foreground "white"))
                        (,class-8 (:foreground "white"))))
   `(erc-notice-face ((,class-88 (:foreground "gray" :weight bold))
                      (,class-8 (:foreground "gray" :weight bold))))
   `(erc-pal-face ((,class-88 (:foreground "white" :weight bold))
                   (,class-8 (:foreground "white" :weight bold))))
   `(erc-prompt-face ((,class-88 (:background "#000000" :foreground "#ffffff" :weight bold))
                      (,class-8 (:background "black" :foreground "white" :weight bold))))
   `(erc-timestamp-face ((,class-88 (:foreground "white"))
                         (,class-8 (:foreground "white"))))
   `(erc-underline-face ((,class-88 (:underline t))
                         (,class-8 (:underline t))))

   ;; Magit (Extended) - duplicated entries merged or verified above.
   ;; (Note: Some magit entries appeared twice in previous tool output due to patching logic.
   ;; I will ensure all remaining general faces are covered.)

   ;; Git Gutter / Diff HL
   `(diff-hl-change ((,class-88 (:background "#000000" :foreground "#ffffff"))
                     (,class-8 (:background "black" :foreground "white"))))
   `(diff-hl-delete ((,class-88 (:background "#000000" :foreground "#ffffff"))
                     (,class-8 (:background "black" :foreground "white"))))
   `(diff-hl-insert ((,class-88 (:background "#000000" :foreground "#ffffff"))
                     (,class-8 (:background "black" :foreground "white"))))

   ;; Compilation
   `(compilation-column-number ((,class-88 (:foreground "white"))
                                (,class-8 (:foreground "white"))))
   `(compilation-error ((,class-88 (:foreground "white" :weight bold))
                        (,class-8 (:foreground "white" :weight bold))))
   `(compilation-info ((,class-88 (:foreground "white"))
                       (,class-8 (:foreground "white"))))
   `(compilation-line-number ((,class-88 (:foreground "white"))
                              (,class-8 (:foreground "white"))))
   `(compilation-mode-line-exit ((,class-88 (:foreground "white" :weight bold))
                                 (,class-8 (:foreground "white" :weight bold))))
   `(compilation-mode-line-fail ((,class-88 (:foreground "white" :weight bold))
                                 (,class-8 (:foreground "white" :weight bold))))
   `(compilation-mode-line-run ((,class-88 (:foreground "white" :weight bold))
                                (,class-8 (:foreground "white" :weight bold))))
   `(compilation-warning ((,class-88 (:foreground "white" :weight bold))
                          (,class-8 (:foreground "white" :weight bold))))

   ;; Custom
   `(custom-button ((,class-88 (:background "#333333" :foreground "white" :box (:line-width 1 :style released-button)))
                    (,class-8 (:background "gray20" :foreground "white" :box (:line-width 1 :style released-button)))))
   `(custom-button-mouse ((,class-88 (:background "#666666" :foreground "white" :box (:line-width 1 :style released-button)))
                          (,class-8 (:background "gray40" :foreground "white" :box (:line-width 1 :style released-button)))))
   `(custom-button-pressed ((,class-88 (:background "#333333" :foreground "white" :box (:line-width 1 :style pressed-button)))
                            (,class-8 (:background "gray20" :foreground "white" :box (:line-width 1 :style pressed-button)))))
   `(custom-comment ((,class-88 (:foreground "white"))
                     (,class-8 (:foreground "white"))))
   `(custom-comment-tag ((,class-88 (:foreground "white"))
                         (,class-8 (:foreground "white"))))
   `(custom-documentation ((,class-88 (:foreground "white"))
                           (,class-8 (:foreground "white"))))
   `(custom-group-tag ((,class-88 (:foreground "white" :weight bold))
                       (,class-8 (:foreground "white" :weight bold))))
   `(custom-group-tag-1 ((,class-88 (:foreground "white" :weight bold))
                         (,class-8 (:foreground "white" :weight bold))))
   `(custom-invalid ((,class-88 (:foreground "white" :weight bold))
                     (,class-8 (:foreground "white" :weight bold))))
   `(custom-modified ((,class-88 (:foreground "white"))
                      (,class-8 (:foreground "white"))))
   `(custom-rogue ((,class-88 (:foreground "white"))
                   (,class-8 (:foreground "white"))))
   `(custom-state ((,class-88 (:foreground "white"))
                   (,class-8 (:foreground "white"))))
   `(custom-themed ((,class-88 (:foreground "white"))
                    (,class-8 (:foreground "white"))))
   `(custom-variable-button ((,class-88 (:weight bold :underline t))
                             (,class-8 (:weight bold :underline t))))
   `(custom-variable-tag ((,class-88 (:foreground "white" :weight bold))
                          (,class-8 (:foreground "white" :weight bold))))
   `(custom-visibility ((,class-88 (:foreground "white" :underline t))
                        (,class-8 (:foreground "white" :underline t))))

   ;; Widget
   `(widget-button ((,class-88 (:weight bold :underline t))
                    (,class-8 (:weight bold :underline t))))
   `(widget-button-pressed ((,class-88 (:foreground "white"))
                            (,class-8 (:foreground "white"))))
   `(widget-documentation ((,class-88 (:foreground "white"))
                           (,class-8 (:foreground "white"))))
   `(widget-field ((,class-88 (:background "#333333" :foreground "white"))
                   (,class-8 (:background "gray20" :foreground "white"))))
   `(widget-single-line-field ((,class-88 (:background "#333333" :foreground "white"))
                               (,class-8 (:background "gray20" :foreground "white"))))

   ;; Diff
   `(diff-added ((,class-88 (:foreground "white"))
                 (,class-8 (:foreground "white"))))
   `(diff-changed ((,class-88 (:foreground "white"))
                   (,class-8 (:foreground "white"))))
   `(diff-context ((,class-88 (:foreground "white"))
                   (,class-8 (:foreground "white"))))
   `(diff-file-header ((,class-88 (:background "#000000" :foreground "#ffffff" :weight bold))
                       (,class-8 (:background "black" :foreground "white" :weight bold))))
   `(diff-function ((,class-88 (:foreground "white"))
                    (,class-8 (:foreground "white"))))
   `(diff-header ((,class-88 (:background "#000000" :foreground "#ffffff"))
                  (,class-8 (:background "black" :foreground "white"))))
   `(diff-hunk-header ((,class-88 (:background "#000000" :foreground "#ffffff"))
                       (,class-8 (:background "black" :foreground "white"))))
   `(diff-index ((,class-88 (:foreground "white"))
                 (,class-8 (:foreground "white"))))
   `(diff-indicator-added ((,class-88 (:foreground "white"))
                           (,class-8 (:foreground "white"))))
   `(diff-indicator-changed ((,class-88 (:foreground "white"))
                             (,class-8 (:foreground "white"))))
   `(diff-indicator-removed ((,class-88 (:foreground "white"))
                             (,class-8 (:foreground "white"))))
   `(diff-nonexistent ((,class-88 (:foreground "white"))
                       (,class-8 (:foreground "white"))))
   `(diff-refine-added ((,class-88 (:background "#333333" :foreground "white"))
                        (,class-8 (:background "gray20" :foreground "white"))))
   `(diff-refine-changed ((,class-88 (:background "#333333" :foreground "white"))
                          (,class-8 (:background "gray20" :foreground "white"))))
   `(diff-refine-removed ((,class-88 (:background "#333333" :foreground "white"))
                          (,class-8 (:background "gray20" :foreground "white"))))
   `(diff-removed ((,class-88 (:foreground "white"))
                   (,class-8 (:foreground "white"))))

   ;; Flymake
   `(flymake-error ((,class-88 (:underline (:style wave :color "white")))
                    (,class-8 (:underline (:style wave :color "white")))))
   `(flymake-note ((,class-88 (:underline (:style wave :color "white")))
                   (,class-8 (:underline (:style wave :color "white")))))
   `(flymake-warning ((,class-88 (:underline (:style wave :color "white")))
                      (,class-8 (:underline (:style wave :color "white")))))

   ;; Terminal / Eshell
   `(eshell-ls-archive ((,class-88 (:foreground "white" :weight bold))
                        (,class-8 (:foreground "white" :weight bold))))
   `(eshell-ls-backup ((,class-88 (:foreground "gray"))
                       (,class-8 (:foreground "gray"))))
   `(eshell-ls-clutter ((,class-88 (:foreground "gray"))
                        (,class-8 (:foreground "gray"))))
   `(eshell-ls-directory ((,class-88 (:foreground "white" :weight bold))
                          (,class-8 (:foreground "white" :weight bold))))
   `(eshell-ls-executable ((,class-88 (:foreground "white" :weight bold))
                           (,class-8 (:foreground "white" :weight bold))))
   `(eshell-ls-missing ((,class-88 (:foreground "white" :weight bold))
                        (,class-8 (:foreground "white" :weight bold))))
   `(eshell-ls-product ((,class-88 (:foreground "white"))
                        (,class-8 (:foreground "white"))))
   `(eshell-ls-readonly ((,class-88 (:foreground "white"))
                         (,class-8 (:foreground "white"))))
   `(eshell-ls-symlink ((,class-88 (:foreground "white" :weight bold))
                        (,class-8 (:foreground "white" :weight bold))))
   `(eshell-ls-unreadable ((,class-88 (:foreground "gray"))
                           (,class-8 (:foreground "gray"))))
   `(eshell-prompt ((,class-88 (:foreground "white" :weight bold))
                    (,class-8 (:foreground "white" :weight bold))))

   ;; Tab Bar / Tab Line
   `(tab-bar ((,class-88 (:background "#000000" :foreground "#ffffff" :box nil))
              (,class-8 (:background "black" :foreground "white" :box nil))))
   `(tab-bar-tab ((,class-88 (:background "#000000" :foreground "#ffffff" :box nil :weight bold))
                  (,class-8 (:background "black" :foreground "white" :box nil :weight bold))))
   `(tab-bar-tab-inactive ((,class-88 (:background "#000000" :foreground "#888888" :box nil))
                           (,class-8 (:background "black" :foreground "gray" :box nil))))
   `(tab-line ((,class-88 (:background "#000000" :foreground "#ffffff"))
               (,class-8 (:background "black" :foreground "white"))))
   `(tab-line-tab ((,class-88 (:background "#000000" :foreground "#ffffff" :weight bold))
                   (,class-8 (:background "black" :foreground "white" :weight bold))))
   `(tab-line-tab-inactive ((,class-88 (:background "#000000" :foreground "#888888"))
                            (,class-8 (:background "black" :foreground "gray"))))
   `(tab-line-tab-current ((,class-88 (:background "#000000" :foreground "#ffffff" :weight bold))
                           (,class-8 (:background "black" :foreground "white" :weight bold))))

   ;; Helm (if used)
   `(helm-header ((,class-88 (:background "#000000" :foreground "#ffffff" :underline nil))
                  (,class-8 (:background "black" :foreground "white" :underline nil))))
   `(helm-source-header ((,class-88 (:background "#000000" :foreground "#ffffff" :weight bold))
                         (,class-8 (:background "black" :foreground "white" :weight bold))))
   `(helm-selection ((,class-88 (:background "#000044" :foreground "white"))
                     (,class-8 (:background "dark blue" :foreground "white"))))
   `(helm-selection-line ((,class-88 (:background "#000044" :foreground "white"))
                          (,class-8 (:background "dark blue" :foreground "white"))))
   `(helm-visible-mark ((,class-88 (:background "#000000" :foreground "#ffffff" :weight bold))
                        (,class-8 (:background "black" :foreground "white" :weight bold))))
   `(helm-candidate-number ((,class-88 (:background "#000000" :foreground "#ffffff"))
                            (,class-8 (:background "black" :foreground "white"))))
   `(helm-separator ((,class-88 (:foreground "white"))
                     (,class-8 (:foreground "white"))))
   `(helm-moccur-buffer ((,class-88 (:foreground "white" :underline t))
                         (,class-8 (:foreground "white" :underline t))))

   ;; Idyll / Prose (Misc)
   `(variable-pitch ((,class-88 (:foreground "white"))
                     (,class-8 (:foreground "white"))))
   `(fixed-pitch ((,class-88 (:foreground "white"))
                  (,class-8 (:foreground "white"))))))

(provide-theme 'tty-dark)

;;; tty-dark-theme.el ends here
