#!/bin/sh
. ~/.config/dmenu/config

search() {
    query=$(printf '' | dmenu $DMENU_BASIC_ARGS -fn "$DMENU_FONT" -i -p "Search $1: ")
    [ -z "$query" ] && return
    encoded=$(python3 -c 'import sys,urllib.parse;print(urllib.parse.quote_plus(sys.argv[1]))' "$query")
    eval "$2"
}

case "$(printf "Firefox\nFirefox Private\nGoogle Chrome\nTor Browser\nBookmarks\nUpload Selection\nGmail\nWhatsApp\nTelegram\nYouTube\nGoogle Calendar\nSearch Google\nSearch Yandex\nSearch Wiby\nSearch Wikipedia\nSearch YouTube\nSearch Yeetube\nYouTube to MPV" | dmenu $DMENU_BASIC_ARGS -fn "$DMENU_FONT" -i -p 'Web:')" in
    'Firefox') firefox --new-window ;;
    'Firefox Private') firefox --private-window ;;
    'Google Chrome') /usr/bin/distrobox-enter -n archbox -- /usr/bin/google-chrome-stable ;;
    'Tor Browser') tor-browser ;;
    'Bookmarks') dmenu-bookmarks ;;
    'Upload Selection') upload-selection ;;
    'Gmail') firefox --new-window "https://mail.google.com/" ;;
    'WhatsApp') firefox --new-window "https://web.whatsapp.com/" ;;
    'Telegram') firefox --new-window "https://web.telegram.org/" ;;
    'YouTube') firefox --new-window "https://www.youtube.com/" ;;
    'Google Calendar') firefox --new-window "https://calendar.google.com/" ;;
    'Search Google') search "Google" 'firefox --new-window "https://www.google.com/search?q=${encoded}"' ;;
    'Search Yandex') search "Yandex" 'firefox --new-window "https://yandex.com/search/?text=${encoded}"' ;;
    'Search Wiby') search "Wiby" 'firefox --new-window "http://wiby.me/?q=${encoded}"' ;;
    'Search Wikipedia') search "Wikipedia" 'firefox --new-window "https://en.wikipedia.org/wiki/Special:Search?search=${encoded}"' ;;
    'Search YouTube') search "YouTube" 'firefox --new-window "https://www.youtube.com/results?search_query=${encoded}"' ;;
    'Search Yeetube') search "Yeetube" 'emacsclient -c -a "" --eval "(yeetube-search \"${query}\")"' ;;
    'YouTube to MPV') browser-to-mpv ;;
    *) exit 1 ;;
esac
