#!/bin/sh
. ~/.config/dmenu/config

choice="$(printf "Lock\nKill X\nReboot\nPoweroff\nHibernate\nDisplay Off\nLogout\nReload Desktop\nClean Local Bin\nDeploy Dotfiles\nScreenshot\nBrightness\nNight\nDay\nTheme Toggle\nTheme Dark\nTheme Light\nBattery Time Left\nStorage Free" | dmenu $DMENU_BASIC_ARGS -fn "$DMENU_FONT" -i -p 'System:')"

case "$choice" in
    'Lock') slock ;;
    'Kill X') pkill X ;;
    'Reboot') systemctl reboot -i ;;
    'Poweroff') systemctl poweroff -i ;;
    'Hibernate') slock & sleep 0.2 && systemctl hibernate ;;
    'Display Off') xset dpms force off ;;
    'Logout') sys-logout ;;
    'Reload Desktop') reload-desktop ;;
    'Clean Local Bin') clean-local-bin ;;
    'Deploy Dotfiles') deploy-dotfiles ;;
    'Screenshot') dmenu-screenshot ;;
    'Brightness')
        level="$(seq 5 5 100 | dmenu $DMENU_BASIC_ARGS -fn "$DMENU_FONT" -i -p 'Brightness:')"
        [ -n "$level" ] && brightnessctl set "${level}%"
        ;;
    'Night') night ;;
    'Day') day ;;
    'Theme Toggle') theme --toggle ;;
    'Theme Dark') theme --dark ;;
    'Theme Light') theme --light ;;
    'Battery Time Left') notify-send "Battery Time Left" "$(battery-time)" ;;
    'Storage Free') storage-notify ;;
    *) exit 1 ;;
esac