"""Tests for the dns CLI (resolver switching)."""

import subprocess

import pytest

from helpers import get_bin_path, import_script

dns = import_script(get_bin_path("dns"))


class TestParseResolvConf:
    def test_extracts_nameservers(self):
        text = ("# generated by NetworkManager\n"
                "search lan\n"
                "nameserver 192.168.1.1\n"
                "nameserver 1.1.1.1\n")
        assert dns.parse_resolv_conf(text) == ["192.168.1.1", "1.1.1.1"]

    def test_ignores_commented_lines(self):
        text = "#nameserver 8.8.8.8\nnameserver 9.9.9.9\n"
        assert dns.parse_resolv_conf(text) == ["9.9.9.9"]

    def test_empty(self):
        assert dns.parse_resolv_conf("") == []


class TestParseServers:
    def test_preset(self):
        assert dns.parse_servers(["cloudflare"]) == ["1.1.1.1", "1.0.0.1"]

    def test_custom_ips(self):
        assert dns.parse_servers(["192.168.1.5", "9.9.9.9"]) == \
            ["192.168.1.5", "9.9.9.9"]

    def test_ipv6_accepted(self):
        assert dns.parse_servers(["2606:4700:4700::1111"]) == \
            ["2606:4700:4700::1111"]

    def test_garbage_dies(self):
        with pytest.raises(SystemExit):
            dns.parse_servers(["not-an-ip"])


class TestCmdSet:
    def _capture_runs(self, monkeypatch):
        calls = []

        def fake_run(cmd, timeout=15):
            calls.append(cmd)
            return subprocess.CompletedProcess(cmd, 0, "", "")

        monkeypatch.setattr(dns, "run", fake_run)
        monkeypatch.setattr(dns, "_resolve_target",
                            lambda name=None: ("HomeWifi", "wlan0"))
        return calls

    def test_preset_sets_servers_and_ignore_auto(self, monkeypatch):
        calls = self._capture_runs(monkeypatch)
        dns.cmd_set(["cloudflare"])
        modify = next(c for c in calls if "modify" in c)
        assert "HomeWifi" in modify
        assert "1.1.1.1 1.0.0.1" in modify
        idx = modify.index("ipv4.ignore-auto-dns")
        assert modify[idx + 1] == "yes"
        # Connection was bounced to apply
        assert any(c[:3] == ["nmcli", "connection", "up"] for c in calls)

    def test_auto_clears_and_restores_dhcp(self, monkeypatch):
        calls = self._capture_runs(monkeypatch)
        dns.cmd_set(["auto"])
        modify = next(c for c in calls if "modify" in c)
        idx = modify.index("ipv4.dns")
        assert modify[idx + 1] == ""
        idx = modify.index("ipv4.ignore-auto-dns")
        assert modify[idx + 1] == "no"

    def test_no_args_dies(self, monkeypatch):
        self._capture_runs(monkeypatch)
        with pytest.raises(SystemExit):
            dns.cmd_set([])
