#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			# set the background with the `setbg` script
mpd &			# music player daemon
remaps &		# run the remaps script,
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/ff_xresources & # added my own xresources

# ff additions:
parcellite &
sleep 60 && python3 ${XDG_CONFIG_HOME:-$HOME/.config}/x11/run_ccursereminders2.py 30 & 
sleep 30 && python3 ${XDG_CONFIG_HOME:-$HOME/.config}/x11/run_ccursereminders2.py 30 & 
sleep 5 && python3 ${XDG_CONFIG_HOME:-$HOME/.config}/x11/run_ccursereminders2.py 5 & 
sleep 1 && python3 ${XDG_CONFIG_HOME:-$HOME/.config}/x11/run_ccursereminders2.py 1 & 
syncthing -no-browser &
nicotine --hidden &
emacs --daemon &
# sleep 10 && python3 /home/ff/d/python/run_ccursereminders2.py 10 &
# sleep 5 && python3 /home/ff/d/python/run_ccursereminders2.py 5 &
# sleep 1 && python3 /home/ff/d/python/run_ccursereminders2.py 1 &

# Mar 26, 2022 -- testing if this is fixed...:
xset -dpms &
xset s off &
xset s off -dpms &

# when booting up my computer, I will manually source this until I learn how to do this in shell scripting language
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh &
