#!/bin/sh

# BSPWM Configuration

#### WORKSPACES ####
# Create 6 workspaces
bspc monitor -d 1 2 3 4 5 6

# Set all desktops to Monocle layout by default
for desktop in $(bspc query -D); do
	bspc desktop $desktop -l monocle
done

#### WINDOW APPEARANCE ####
# Border width
bspc config border_width         3

# Window gaps
bspc config window_gap           2

# Border colors
bspc config normal_border_color  "#222222"   # normbordercolor
bspc config active_border_color  "#222222"
bspc config focused_border_color "#8b1a1a"   # selbordercolor
bspc config presel_feedback_color  "#8b1a1a"

#### WINDOW BEHAVIOR ####
bspc config split_ratio          0.50        # evenly split
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       false

#### POINTER BEHAVIOR ####
bspc config pointer_modifier     mod4        # Super key (MODKEY)
bspc config pointer_action1      move        # mod4+button1 = move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner # mod4+button3 = resize

bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

#### WINDOW RULES ####
# BSPWM doesn't have native swallowing, but we'll set up basic rules



#### AUTOSTART ####
# Launch SXHKD (keybinding daemon)
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch Polybar
pgrep -x polybar > /dev/null || polybar mybar &
